# Dev profile: verbose logging + convenient defaults
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 3000

logging:
  level:
    root: INFO
    com.mipt.popikovdmitriy: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO