# Prod profile: safer defaults for production
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080
  shutdown: graceful
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

logging:
  level:
    root: INFO
    com.mipt.popikovdmitriy: INFO
    org.springframework: WARN